// GENERATED CODE - DO NOT MODIFY BY HAND

// coverage:ignore-file
// ignore_for_file: cast_nullable_to_non_nullable, unnecessary_null_checks,  unnecessary_lambdas, inference_failure_on_collection_literal, unused_element

part of 'service_order.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ServiceOrder _$ServiceOrderFromJson(
  Map<String, dynamic> json,
) => $checkedCreate('ServiceOrder', json, ($checkedConvert) {
  final val = ServiceOrder(
    id: $checkedConvert('id', (v) => v as String),
    storeId: $checkedConvert('storeId', (v) => v as String),
    number: $checkedConvert('number', (v) => (v as num).toInt()),
    customerId: $checkedConvert('customerId', (v) => v as String),
    deviceId: $checkedConvert('deviceId', (v) => v as String),
    status: $checkedConvert('status', (v) => $enumDecode(_$ServiceOrderStatusEnumMap, v)),
    reportedIssue: $checkedConvert('reportedIssue', (v) => v as String),
    hasBackup: $checkedConvert('hasBackup', (v) => v as bool),
    totalValue: $checkedConvert('totalValue', (v) => MoneyAmount.fromJson(v)),
    partsTotal: $checkedConvert('partsTotal', (v) => MoneyAmount.fromJson(v)),
    laborTotal: $checkedConvert('laborTotal', (v) => MoneyAmount.fromJson(v)),
    warrantyDays: $checkedConvert('warrantyDays', (v) => (v as num).toInt()),
    isOverdue: $checkedConvert('isOverdue', (v) => v as bool),
    isUnderWarranty: $checkedConvert('isUnderWarranty', (v) => v as bool),
    items: $checkedConvert(
      'items',
      (v) => (v as List<dynamic>)
          .map((e) => ServiceOrderItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    ),
    createdAt: $checkedConvert('createdAt', (v) => ApiInstant.fromJson(v as Map<String, dynamic>)),
    updatedAt: $checkedConvert('updatedAt', (v) => ApiInstant.fromJson(v as Map<String, dynamic>)),
    technicianId: $checkedConvert('technicianId', (v) => v as String?),
    accessories: $checkedConvert('accessories', (v) => v as String?),
    deviceCondition: $checkedConvert(
      'deviceCondition',
      (v) => v == null ? null : DeviceEntryCondition.fromJson(v as Map<String, dynamic>),
    ),
    unlockCode: $checkedConvert('unlockCode', (v) => v as String?),
    diagnosis: $checkedConvert('diagnosis', (v) => v as String?),
    quoteValue: $checkedConvert('quoteValue', (v) => v == null ? null : MoneyAmount.fromJson(v)),
    quoteSentAt: $checkedConvert(
      'quoteSentAt',
      (v) => v == null ? null : ApiInstant.fromJson(v as Map<String, dynamic>),
    ),
    approvedAt: $checkedConvert(
      'approvedAt',
      (v) => v == null ? null : ApiInstant.fromJson(v as Map<String, dynamic>),
    ),
    approvedByName: $checkedConvert('approvedByName', (v) => v as String?),
    rejectionReason: $checkedConvert('rejectionReason', (v) => v as String?),
    promisedDate: $checkedConvert(
      'promisedDate',
      (v) => v == null ? null : CalendarDate.fromJson(v),
    ),
    repairNotes: $checkedConvert('repairNotes', (v) => v as String?),
    deliveredAt: $checkedConvert(
      'deliveredAt',
      (v) => v == null ? null : ApiInstant.fromJson(v as Map<String, dynamic>),
    ),
    deliveredToName: $checkedConvert('deliveredToName', (v) => v as String?),
    warrantyExpiresAt: $checkedConvert(
      'warrantyExpiresAt',
      (v) => v == null ? null : CalendarDate.fromJson(v),
    ),
    invoiceId: $checkedConvert('invoiceId', (v) => v as String?),
    createdBy: $checkedConvert('createdBy', (v) => v as String?),
  );
  return val;
});

Map<String, dynamic> _$ServiceOrderToJson(ServiceOrder instance) => <String, dynamic>{
  'id': instance.id,
  'storeId': instance.storeId,
  'number': instance.number,
  'customerId': instance.customerId,
  'deviceId': instance.deviceId,
  'status': _$ServiceOrderStatusEnumMap[instance.status]!,
  'technicianId': instance.technicianId,
  'reportedIssue': instance.reportedIssue,
  'accessories': instance.accessories,
  'deviceCondition': instance.deviceCondition?.toJson(),
  'unlockCode': instance.unlockCode,
  'hasBackup': instance.hasBackup,
  'diagnosis': instance.diagnosis,
  'quoteValue': instance.quoteValue?.toJson(),
  'quoteSentAt': instance.quoteSentAt?.toJson(),
  'approvedAt': instance.approvedAt?.toJson(),
  'approvedByName': instance.approvedByName,
  'rejectionReason': instance.rejectionReason,
  'promisedDate': instance.promisedDate?.toJson(),
  'repairNotes': instance.repairNotes,
  'totalValue': instance.totalValue.toJson(),
  'partsTotal': instance.partsTotal.toJson(),
  'laborTotal': instance.laborTotal.toJson(),
  'warrantyDays': instance.warrantyDays,
  'deliveredAt': instance.deliveredAt?.toJson(),
  'deliveredToName': instance.deliveredToName,
  'warrantyExpiresAt': instance.warrantyExpiresAt?.toJson(),
  'invoiceId': instance.invoiceId,
  'isOverdue': instance.isOverdue,
  'isUnderWarranty': instance.isUnderWarranty,
  'items': instance.items.map((e) => e.toJson()).toList(),
  'createdBy': instance.createdBy,
  'createdAt': instance.createdAt.toJson(),
  'updatedAt': instance.updatedAt.toJson(),
};

const _$ServiceOrderJsonSchema = {
  r'$schema': 'https://json-schema.org/draft/2020-12/schema',
  'type': 'object',
  'properties': {
    'id': {'type': 'string', 'description': 'UUID.'},
    'storeId': {'type': 'string', 'description': 'Loja.'},
    'number': {'type': 'integer', 'description': 'Sequencial por loja.'},
    'customerId': {'type': 'string', 'description': 'Cliente.'},
    'deviceId': {'type': 'string', 'description': 'Aparelho.'},
    'status': {'type': 'object', 'description': 'Situação.'},
    'technicianId': {'type': 'string', 'description': 'Técnico, ou `null`.'},
    'reportedIssue': {'type': 'string', 'description': 'Defeito relatado.'},
    'accessories': {'type': 'string', 'description': 'Acessórios, ou `null`.'},
    'deviceCondition': {
      r'$ref': r'#/$defs/DeviceEntryCondition',
      'description': 'Checklist de entrada, ou `null`.',
    },
    'unlockCode': {
      'type': 'string',
      'description': 'Senha ou padrão. `null` na listagem e sem a permissão de atualização.',
    },
    'hasBackup': {'type': 'boolean', 'description': 'Se foi feito backup.'},
    'diagnosis': {'type': 'string', 'description': 'Diagnóstico, ou `null`.'},
    'quoteValue': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Valor orçado, ou `null`.'},
    'quoteSentAt': {
      r'$ref': r'#/$defs/ApiInstant',
      'description': 'Envio do orçamento, ou `null`.',
    },
    'approvedAt': {r'$ref': r'#/$defs/ApiInstant', 'description': 'Aprovação, ou `null`.'},
    'approvedByName': {'type': 'string', 'description': 'Quem autorizou pelo cliente, ou `null`.'},
    'rejectionReason': {'type': 'string', 'description': 'Motivo da recusa, ou `null`.'},
    'promisedDate': {
      r'$ref': r'#/$defs/CalendarDate',
      'description': 'Prazo prometido, ou `null`.',
    },
    'repairNotes': {'type': 'string', 'description': 'Notas de execução, ou `null`.'},
    'totalValue': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Soma dos itens.'},
    'partsTotal': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Soma das peças.'},
    'laborTotal': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Soma da mão de obra.'},
    'warrantyDays': {'type': 'integer', 'description': 'Garantia em dias.'},
    'deliveredAt': {r'$ref': r'#/$defs/ApiInstant', 'description': 'Entrega, ou `null`.'},
    'deliveredToName': {'type': 'string', 'description': 'Quem retirou, ou `null`.'},
    'warrantyExpiresAt': {
      r'$ref': r'#/$defs/CalendarDate',
      'description': 'Fim da garantia, ou `null`.',
    },
    'invoiceId': {'type': 'string', 'description': 'Nota gerada na entrega, ou `null`.'},
    'isOverdue': {'type': 'boolean', 'description': 'Se o prazo estourou e a ordem segue aberta.'},
    'isUnderWarranty': {'type': 'boolean', 'description': 'Se a garantia ainda vale.'},
    'items': {
      'type': 'array',
      'items': {r'$ref': r'#/$defs/ServiceOrderItem'},
      'description': 'Itens. Lista vazia na fila.',
    },
    'createdBy': {'type': 'string', 'description': 'Autor da abertura, ou `null`.'},
    'createdAt': {r'$ref': r'#/$defs/ApiInstant', 'description': 'Criação.'},
    'updatedAt': {r'$ref': r'#/$defs/ApiInstant', 'description': 'Última alteração.'},
  },
  'required': [
    'id',
    'storeId',
    'number',
    'customerId',
    'deviceId',
    'status',
    'reportedIssue',
    'hasBackup',
    'totalValue',
    'partsTotal',
    'laborTotal',
    'warrantyDays',
    'isOverdue',
    'isUnderWarranty',
    'items',
    'createdAt',
    'updatedAt',
  ],
  r'$defs': {
    'DeviceEntryCondition': {
      'type': 'object',
      'properties': {
        'screenCracked': {'type': 'boolean', 'description': 'Se a tela está trincada.'},
        'touchWorking': {'type': 'boolean', 'description': 'Se o toque funciona.'},
        'housingDamaged': {'type': 'boolean', 'description': 'Se a carcaça está danificada.'},
        'waterDamage': {'type': 'boolean', 'description': 'Se há dano por líquido.'},
        'batterySwollen': {'type': 'boolean', 'description': 'Se a bateria está inchada.'},
        'buttonsWorking': {'type': 'boolean', 'description': 'Se os botões funcionam.'},
        'cameraWorking': {'type': 'boolean', 'description': 'Se a câmera funciona.'},
        'chargingWorking': {'type': 'boolean', 'description': 'Se a carga funciona.'},
        'notes': {'type': 'string', 'description': 'Observação, ou `null`.'},
      },
      'required': [
        'screenCracked',
        'touchWorking',
        'housingDamaged',
        'waterDamage',
        'batterySwollen',
        'buttonsWorking',
        'cameraWorking',
        'chargingWorking',
      ],
    },
    'MoneyAmount': {'type': 'object', 'properties': {}},
    'ApiInstant': {
      'type': 'object',
      'properties': {
        'value': {'type': 'string', 'format': 'date-time', 'description': 'Instante em UTC.'},
      },
      'required': ['value'],
    },
    'CalendarDate': {'type': 'object', 'properties': {}},
    'QuantityAmount': {'type': 'object', 'properties': {}},
    'ServiceOrderItem': {
      'type': 'object',
      'properties': {
        'id': {'type': 'string', 'description': 'UUID.'},
        'serviceOrderId': {'type': 'string', 'description': 'Ordem dona do item.'},
        'productId': {'type': 'string', 'description': 'Peça, ou `null`.'},
        'serviceId': {'type': 'string', 'description': 'Mão de obra, ou `null`.'},
        'description': {'type': 'string', 'description': 'Descrição.'},
        'quantity': {r'$ref': r'#/$defs/QuantityAmount', 'description': 'Quantidade, escala 3.'},
        'unitPrice': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Preço unitário.'},
        'unitCost': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Custo unitário, ou `null`.'},
        'totalValue': {r'$ref': r'#/$defs/MoneyAmount', 'description': 'Total calculado.'},
        'createdAt': {r'$ref': r'#/$defs/ApiInstant', 'description': 'Inclusão.'},
      },
      'required': [
        'id',
        'serviceOrderId',
        'description',
        'quantity',
        'unitPrice',
        'totalValue',
        'createdAt',
      ],
    },
  },
};

const _$ServiceOrderStatusEnumMap = {
  ServiceOrderStatus.received: 'received',
  ServiceOrderStatus.inDiagnosis: 'in_diagnosis',
  ServiceOrderStatus.awaitingApproval: 'awaiting_approval',
  ServiceOrderStatus.approved: 'approved',
  ServiceOrderStatus.rejected: 'rejected',
  ServiceOrderStatus.awaitingParts: 'awaiting_parts',
  ServiceOrderStatus.inRepair: 'in_repair',
  ServiceOrderStatus.ready: 'ready',
  ServiceOrderStatus.delivered: 'delivered',
  ServiceOrderStatus.cancelled: 'cancelled',
  ServiceOrderStatus.returnedUnrepaired: 'returned_unrepaired',
};
